version: "3.8"

services:

  site:
    image: floryn90/hugo:ext-alpine
#    build:
#      context: .
    command: server --poll 700ms --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - .:/src
